---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/julia --version
      register: julia_test_output
    - debug:
        msg: '{{ julia_test_output.stdout }}'
