---
- name: Testing andrewrothstein.julia
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'julia --version'
      ansible.builtin.command: /usr/local/bin/julia --version
      changed_when: false
      register: julia_test_output
    - name: Output from 'julia --version'
      ansible.builtin.debug:
        msg: '{{ julia_test_output.stdout }}'
