---
- name: (Ubuntu) build/vcs deps...
  when: ansible_distribution == 'Ubuntu'
  include: Ubuntu-BuildFromSource-deps.yml

- name: (RedHat) build/vcs deps...
  when: ansible_os_family == 'RedHat'
  include: RedHat-BuildFromSource-deps.yml
  
- name: getting source...
  git: >
    repo={{julia_build_repo}}
    dest={{julia_src_dir}}
    version={{julia_build_branch}}
    accept_hostkey=yes

- name: build it....
  command: make {{julia_build_make_args}}
  args:
    chdir: '{{julia_src_dir}}'

- name: clear out target...
  command: rm -rf {{julia_bin_dir}}

- name: install build...
  command: mv {{julia_src_dir}}/usr {{julia_bin_dir}}

- name: delete intermediate build artifacts
  when: julia_build_cleanup
  command: rm -rf {{julia_src_dir}}
  
- name: link /opt/julia
  file: >-
    src={{julia_bin_dir}}
    dest=/opt/julia
    state=link
    owner=root
    group=root

- name: link /usr/local/bin/julia...
  file: >-
    src=/opt/julia/bin/julia
    dest=/usr/local/bin/julia
    state=link
    owner=root
    group=root
