---
- name: (Debian) julia dep pkgs
  when: ansible_os_family == 'Debian'
  include: Generic-Debian-deps.yml

- name: (RedHat) julia dep pkgs
  when: ansible_os_family == 'RedHat'
  include: Generic-RedHat-deps.yml
    
- name: download julia
  get_url: url={{julia_tgz_url}} dest='/tmp/{{julia_tgz}}'

- name: create /opt/julia-xxx
  file: >-
    owner=root
    group=root
    mode=755
    path=/opt/{{julia_name}}
    state=directory
  
- name: unarchive julia
  command: tar --strip-components=1 -zxvf /tmp/{{julia_tgz}} -C /opt/{{julia_name}}
  args:
    creates: /opt/{{julia_name}}/bin/julia

- name: link /opt/julia
  file: src=/opt/{{julia_name}} dest=/opt/julia state=link

- name: add /opt/julia to the default path
  copy: >-
    src=etc/profile.d/julia.sh
    dest=/etc/profile.d/julia.sh
    mode=644
    owner=root
    group=root
    