---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.alpine-glibc-shim
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for installation in {{ julia_install_dir }}
  become: true
  stat:
    path: '{{ julia_install_dir }}'
  changed_when: false
  register: julia_binary
- when: not julia_binary.stat.exists
  block:
    - name: downloading {{ julia_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ julia_url }}'
        dest: '{{ julia_tmp_tgz }}'
        checksum: '{{ julia_checksum }}'
        mode: 0644
    - name: unarchiving {{ julia_tmp_tgz }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ julia_tmp_tgz }}'
        dest: '{{ julia_parent_install_dir }}'
        creates: '{{ julia_install_dir }}'
  always:
    - name: rm {{ julia_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ julia_tmp_tgz }}'
        state: absent
- name: linking executables in {{ julia_install_dir }}/bin to {{ julia_parent_install_dir }}/bin
  become: true
  become_user: root
  with_items:
    - julia
  file:
    src: '{{ julia_install_dir }}/bin/{{ item }}'
    dest: '{{ julia_parent_install_dir }}/bin/{{ item }}'
    state: link
