---

- name: Ubuntu install
  when: >
    not julia_build_src
    and julia_use_pkgs
    and ansible_distribution == 'Ubuntu'
  include: Ubuntu.yml

- name: CentOS/Fedora install
  when: >
    not julia_build_src
    and julia_use_pkgs
    and (ansible_distribution == 'CentOS'
    or ansible_distribution == 'Fedora')
  include: CentOSFedora.yml

- name: generics install
  when: not julia_build_src and not julia_use_pkgs
  include: Generic.yml

- name: building from source...
  when: julia_build_src
  include: BuildFromSource.yml
  