---
- name: Ubuntu install
  when: ansible_distribution == 'Ubuntu'
  include: Ubuntu.yml

- name: CentOS/Fedora install
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'
  include: CentOSFedora.yml
