---
- name: Ubuntu install
  when: use_pkgs and ansible_distribution == 'Ubuntu'
  include: Ubuntu.yml

- name: CentOS/Fedora install
  when: use_pkgs and (ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora')
  include: CentOSFedora.yml

- name: generics install
  when: not use_pkgs
  include: Generic.yml