---
- name: (Ubuntu) installing dependent pkgs (see julia.git/.travis.yml)
  package: name={{item}} state=latest
  with_items:
    - curl
    - git
    - binutils
    - gcc
    - g++
    - make
    - libssl-dev
    - gfortran
    - m4
    - cmake
    - patch
