---
- name: dependent packages
  apt: name={{item}} state=latest
  with_items:
    - python-apt
    - curl

- name: add staticfloat/julia* ppas
  apt_repository: repo={{ item }}
  with_items:
    - ppa:staticfloat/juliareleases
    - ppa:staticfloat/julia-deps
  
- name: install julia
  apt: name=julia state=latest

