---
- name: (Ubuntu) add staticfloat/julia* ppas
  apt_repository: repo={{ item }}
  with_items:
    - ppa:staticfloat/juliareleases
    - ppa:staticfloat/julia-deps
  
- name: (Ubuntu) install julia
  apt: name=julia state=latest

