---
- name: (Ubuntu) installing dependent pkgs (see julia.git/.travis.yml)
  apt: name={{item}} state=latest
  with_items:
    - git
    - binutils
    - gcc
    - g++
    - make
    - libssl-dev
    - gfortran