---
- name: dependent packages
  package: name={{item}} state=present
  with_items:
    - python-apt
    - curl

- name: add staticfloat/julia* ppas
  apt_repository: repo={{ item }}
  with_items:
    - ppa:staticfloat/juliareleases
    - ppa:staticfloat/julia-deps
  
- name: install julia
  package: name=julia state=present
  
